# Generated by Django 4.1.7 on 2023-03-18 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
