# Generated by Django 4.1.7 on 2023-03-18 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_enquiry_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='Product',
        ),
    ]
